# Generated by Django 4.1 on 2022-10-12 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToDoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_text", models.CharField(max_length=200)),
                ("classroom_API", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.CharField(max_length=1000)),
                ("priority", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=False)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="To_DoZ.history"
                    ),
                ),
                (
                    "to_do_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="To_DoZ.todolist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="history",
            name="to_do_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="To_DoZ.todolist"
            ),
        ),
    ]
