# Generated by Django 4.1 on 2022-10-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("To_DoZ", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="subject_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
