# Generated by Django 4.1 on 2022-10-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("To_DoZ", "0002_history_subject_text"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="history",),
        migrations.DeleteModel(name="History",),
    ]
