# Generated by Django 4.1 on 2022-10-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("To_DoZ", "0003_remove_task_history_delete_history"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist", old_name="subject_text", new_name="subject",
        ),
    ]
