# Generated by Django 4.1.2 on 2022-11-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_DoZ', '0005_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
