# Generated by Django 4.1.2 on 2022-11-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_DoZ', '0008_alter_task_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
