# Generated by Django 4.1 on 2022-11-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_DoZ', '0005_discord_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_url',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
