# Generated by Django 4.1.1 on 2022-11-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_DoZ', '0010_discord_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_url',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
