# Generated by Django 4.1.1 on 2022-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_DoZ', '0012_google_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_token',
            name='expiry',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='google_token',
            name='refresh_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
