# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: create coverage report in main
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage Django python-decouple django-allauth pytest-django django_apscheduler
        pip install discordwebhook
        pip install google-api-python-client
        pip install google-auth-oauthlib
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: create coverage report
      run: |
  
        coverage run manage.py test
        coverage report
        coverage xml
    - name: Overwrite file
      uses: "DamianReeves/write-file-action@master"
      with:
        path: result/.coverage
        write-mode: overwrite
        contents: |
          GITHUB_PATH/.coverage
    - name: Overwrite file xml
      uses: "DamianReeves/write-file-action@master"
      with:
        path: result/coverage.xml
        write-mode: overwrite
        contents: |
          GITHUB_PATH/coverage.xml

    - name: Commit & Push
      uses: Andro999b/push@v1.3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: false
          message: 'Overwritten by Github Actions'
    - name: Upload coverage report using Github Action
      uses: codecov/codecov-action@v3.1.1
